// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Temp_UserNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Temp_UserNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201711180442025_Temp_UserNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
